export const INITIALIZE_STORE = 'INITIALIZE_STORE'
export const UPDATE_HEADER_NAME = 'UPDATE_HEADER_NAME'
export const UPDATE_MENU_STATUS = 'UPDATE_MENU_STATUS'
export const UPDATE_PLAYER_STATUS = 'UPDATE_PLAYER_STATUS'