import styles from './layout.module.scss'
import { Inter } from 'next/font/google'
import Header from '@/components/header'
import Player from '../components/player'
import { AppWrapper } from '@/store'
import LeftMenu from '../components/leftMenu'
import { ReactNode } from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: ReactNode
}) {

  return (
    <html lang="ru" className={styles.htmlContainer}>
      <AppWrapper>
        <body className={inter.className + ' ' + styles.bodyContainer}>
          <Header/>
          <div className={styles.mainContainer}>
            <LeftMenu/>
            {children}
          </div>
        <Player/>
        </body>
      </AppWrapper>
    </html>
  )
}
